export const CONFIG = {
    supportedMediaFileExtensions: [
        ".jpeg",
        ".jpg",
        ".heic",
        ".gif",
        ".mp4",
        ".png",
        ".avi",
        ".mov",
        ".dng",
        ".m4v",
        ".webp",
        ".mpg",
        ".mod",
        ".mmv",
        ".tod",
        ".wmv",
        ".asf",
        ".divx",
        ".3gp",
        ".3g2",
        ".m2t",
        ".m2ts",
        ".mts",
        ".mkv",
    ],
    exifMediaFileExtensions: [".jpeg", ".jpg", ".heic", ".mp4", ".png", ".mov"],
};

// TODO: Check all the formats that Apple Photos supports: .jpg, .png, .webp, .gif, some RAW files, .mpg, .mod, .mmv, .tod, .wmv, .asf, .avi, .divx, .mov, .m4v, .3gp, .3g2, .mp4, .m2t, .m2ts, .mts, and .mkv files.
